// Autogenerated from Pigeon (v18.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

class PigeonTopic {
  PigeonTopic({
    required this.id,
    required this.title,
    required this.description,
    required this.dateTime,
  });

  int id;

  String title;

  String description;

  String dateTime;

  Object encode() {
    return <Object?>[
      id,
      title,
      description,
      dateTime,
    ];
  }

  static PigeonTopic decode(Object result) {
    result as List<Object?>;
    return PigeonTopic(
      id: result[0]! as int,
      title: result[1]! as String,
      description: result[2]! as String,
      dateTime: result[3]! as String,
    );
  }
}

class _FlutterTopicsRepositoryCodec extends StandardMessageCodec {
  const _FlutterTopicsRepositoryCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is PigeonTopic) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return PigeonTopic.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

abstract class FlutterTopicsRepository {
  static const MessageCodec<Object?> pigeonChannelCodec = _FlutterTopicsRepositoryCodec();

  Future<List<PigeonTopic?>> getTopics();

  static void setUp(FlutterTopicsRepository? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.domain.FlutterTopicsRepository.getTopics$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        __pigeon_channel.setMessageHandler(null);
      } else {
        __pigeon_channel.setMessageHandler((Object? message) async {
          try {
            final List<PigeonTopic?> output = await api.getTopics();
            return wrapResponse(result: output);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
