name: topics_flutter
description: "A new Flutter module project."
version: 1.0.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get_it: ^7.6.8
  injectable: ^2.4.1
  flutter_bloc: ^8.1.5
  go_router: ^13.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  go_router_builder:
  build_runner:
  build_verify:

flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: com.example.topics_flutter
    iosBundleIdentifier: com.example.topicsFlutter
