name: topics_flutter
description: "A new Flutter module project."
version: 1.0.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get_it: ^7.6.8
  injectable: ^2.4.1
  flutter_bloc: ^8.1.5
  go_router: ^13.2.2
  equatable: ^2.0.5
  domain:
    path: packages/domain
  data:
    path: packages/data
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  go_router_builder:
  build_runner:
  build_verify:
  injectable_generator:

flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: com.marcosanna.topics
    iosBundleIdentifier: com.marcosanna.topics
